# Generated by Django 5.0 on 2024-01-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="end_date",
            new_name="renovation_date",
        ),
        migrations.RenameField(
            model_name="historicalcontract",
            old_name="end_date",
            new_name="renovation_date",
        ),
        migrations.AddField(
            model_name="contract",
            name="civil_responsibility_policy",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="compliance_policy",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="contact",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="contact_telephone",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="duration",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="insurance_policy",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="monthly_cost",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="civil_responsibility_policy",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="compliance_policy",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="contact",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="contact_telephone",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="duration",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="insurance_policy",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="monthly_cost",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contract",
            name="description",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="historicalcontract",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
