# Generated by Django 5.0 on 2024-01-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0003_alter_contract_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="city",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="expected_start_date",
            field=models.DateField(default="2023-12-22"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="city",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcontract",
            name="expected_start_date",
            field=models.DateField(default="2023-12-22"),
            preserve_default=False,
        ),
    ]
