# Generated by Django 5.0.2 on 2024-06-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Management',
        ),
    ]
