# Generated by Django 5.0.7 on 2024-08-21 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0005_alter_area_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='hierarchy.area'),
        ),
    ]
