# Generated by Django 5.0.7 on 2024-09-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0006_area_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'permissions': [('manage_area', 'Can manage the area')]},
        ),
    ]
