version: '3.4'
services:
    vite_docker:
        image: node:alpine
        container_name: insights_container
        entrypoint: /bin/sh
        ports:
            - 172.16.0.115:8000:8000
        working_dir: /srv/app
        volumes:
            - type: bind
              source: ./
              target: /srv/app
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: ['./start.sh']
