# Generated by Django 5.0 on 2023-12-21 15:17

import sgc.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sgc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sgcfile",
            name="file",
            field=models.FileField(upload_to="files/SGC/"),
        ),
    ]
