# Generated by Django 5.0 on 2023-12-26 09:21

import django.core.validators
import sgc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0002_alter_sgcfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgcfile',
            name='version',
            field=models.CharField(default='1.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='sgcfile',
            name='file',
            field=models.FileField(upload_to='files/SGC/', validators=[django.core.validators.FileExtensionValidator(['.xlsx', '.pdf', '.docx', '.doc', '.pptx']), sgc.models.file_content_validator]),
        ),
    ]
