# Generated by Django 5.0 on 2023-12-29 14:25

import django.core.validators
import sgc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0008_alter_sgcfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgcfile',
            name='file',
            field=models.FileField(upload_to='files/SGC/', validators=[django.core.validators.FileExtensionValidator(['xlsx', 'pdf', 'docx', 'doc', 'pptx']), sgc.models.file_content_validator]),
        ),
    ]
