# Generated by Django 5.0 on 2024-01-26 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
        ('sgc', '0011_alter_sgcfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgcfile',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hierarchy.area'),
        ),
    ]
