# Generated by Django 5.0 on 2024-01-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0012_alter_sgcfile_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='SGCArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
