# Generated by Django 5.0 on 2024-01-26 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgc', '0013_sgcarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgcfile',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgc.sgcarea'),
        ),
    ]
