# Generated by Django 5.0.8 on 2024-10-07 14:35

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('users', '0001_squashed_0006_user_cedula'), ('users', '0007_alter_user_cedula_alter_user_password'), ('users', '0008_alter_user_cedula'), ('users', '0009_alter_user_managers_alter_user_cedula'), ('users', '0010_user_email'), ('users', '0011_user_is_staff_user_is_superuser'), ('users', '0012_remove_user_is_staff'), ('users', '0013_user_is_staff'), ('users', '0014_remove_user_profile_picture'), ('users', '0015_alter_user_email'), ('users', '0016_alter_user_cedula'), ('users', '0017_alter_user_options'), ('users', '0018_alter_user_last_name'), ('users', '0019_alter_user_last_name'), ('users', '0020_alter_user_last_name_alter_user_username'), ('users', '0021_alter_user_last_name_alter_user_username'), ('users', '0022_alter_user_options'), ('users', '0023_user_job_position'), ('users', '0024_remove_user_job_title'), ('users', '0025_alter_user_job_position'), ('users', '0026_user_company_mail'), ('users', '0027_rename_company_mail_user_company_email'), ('users', '0028_user_points'), ('users', '0029_alter_user_options'), ('users', '0030_user_last_login')]

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hierarchy', '0001_initial'),
        ('hierarchy', '0003_jobposition'),
        ('hierarchy', '0004_area_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='hierarchy.area')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('job_position', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='hierarchy.jobposition')),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('points', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'permissions': [('upload_robinson_list', 'Can upload robinson list'), ('upload_points', 'Can upload points')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
