# Generated by Django 4.2.5 on 2023-11-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_cedula_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.IntegerField(null=True),
        ),
    ]
