# Generated by Django 5.0 on 2024-01-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
