# Generated by Django 5.0.2 on 2024-03-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_cedula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('upload_robinson_list', 'Can upload robinson list'), ('send_employment_certification', 'Can send employment certification')]},
        ),
    ]
