# Generated by Django 5.0.2 on 2024-04-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_last_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('upload_robinson_list', 'Can upload robinson list')]},
        ),
    ]
