# Generated by Django 5.0.2 on 2024-06-04 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0003_jobposition'),
        ('users', '0022_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='hierarchy.jobposition'),
        ),
    ]
