# Generated by Django 5.0.2 on 2024-07-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_job_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job_title',
        ),
    ]
