# Generated by Django 5.0.7 on 2024-08-05 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0004_area_manager'),
        ('users', '0024_remove_user_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_position',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='hierarchy.jobposition'),
            preserve_default=False,
        ),
    ]
