# Generated by Django 5.0.7 on 2024-08-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_company_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company_mail',
            new_name='company_email',
        ),
    ]
