# Generated by Django 5.0.7 on 2024-08-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_user_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('upload_robinson_list', 'Can upload robinson list'), ('upload_points', 'Can upload points')]},
        ),
    ]
