# Generated by Django 5.0.8 on 2024-10-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0008_area_manager'),
        ('users', '0001_squashed_0006_user_cedula_squashed_0030_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='hierarchy.jobposition'),
        ),
    ]
