# Generated by Django 5.0.2 on 2024-03-14 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario')),
                ('contract_type', models.CharField(max_length=100, verbose_name='Tipo de contrato')),
                ('expedition_city', models.CharField(max_length=100, verbose_name='Ciudad de expedición')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_certifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
