# Generated by Django 5.0.2 on 2024-03-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmentcertification',
            options={'default_permissions': (), 'permissions': [('get_employment_certification', 'Can get employment certification')]},
        ),
    ]
