# Generated by Django 5.0.2 on 2024-04-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment_management', '0002_alter_employmentcertification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentcertification',
            name='bonuses',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Bonificaciones'),
        ),
    ]
