# Generated by Django 4.2.5 on 2023-11-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='campaign',
            new_name='campaign_execution',
        ),
        migrations.RenameField(
            model_name='goals',
            old_name='coordinator',
            new_name='coordinator_execution',
        ),
        migrations.RenameField(
            model_name='goals',
            old_name='criteria',
            new_name='criteria_execution',
        ),
        migrations.RenameField(
            model_name='goals',
            old_name='job_title',
            new_name='job_title_execution',
        ),
        migrations.RenameField(
            model_name='goals',
            old_name='quantity',
            new_name='quantity_execution',
        ),
        migrations.RenameField(
            model_name='goals',
            old_name='status',
            new_name='status_execution',
        ),
        migrations.RenameField(
            model_name='historicalgoals',
            old_name='campaign',
            new_name='campaign_execution',
        ),
        migrations.RenameField(
            model_name='historicalgoals',
            old_name='criteria',
            new_name='campaign_goal',
        ),
        migrations.RenameField(
            model_name='historicalgoals',
            old_name='coordinator',
            new_name='coordinator_execution',
        ),
        migrations.RenameField(
            model_name='historicalgoals',
            old_name='job_title',
            new_name='coordinator_goal',
        ),
        migrations.RenameField(
            model_name='historicalgoals',
            old_name='quantity',
            new_name='quantity_execution',
        ),
        migrations.RenameField(
            model_name='historicalgoals',
            old_name='status',
            new_name='status_execution',
        ),
        migrations.AddField(
            model_name='goals',
            name='campaign_goal',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goals',
            name='coordinator_goal',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goals',
            name='criteria_goal',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goals',
            name='job_title_goal',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goals',
            name='quantity_goal',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goals',
            name='status_goal',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalgoals',
            name='criteria_execution',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgoals',
            name='criteria_goal',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgoals',
            name='job_title_execution',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgoals',
            name='job_title_goal',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgoals',
            name='quantity_goal',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgoals',
            name='status_goal',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
