# Generated by Django 4.2.5 on 2023-11-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_rename_campaign_goals_campaign_execution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='observation',
            new_name='observation_execution',
        ),
        migrations.RenameField(
            model_name='historicalgoals',
            old_name='observation',
            new_name='observation_execution',
        ),
        migrations.AddField(
            model_name='goals',
            name='observation_goal',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='historicalgoals',
            name='observation_goal',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
