# Generated by Django 5.0.2 on 2024-05-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_alter_goals_campaign_execution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalgoals',
            name='cedula',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
