# Generated by Django 4.2.5 on 2023-11-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excels_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excelsmodels',
            options={'managed': False, 'permissions': (('call_transfer', 'Can change the path of the calls to the another location'),)},
        ),
    ]
