# Generated by Django 5.0.2 on 2024-05-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0003_alter_vacationrequest_uploaded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacationrequest',
            old_name='request_pdf',
            new_name='request_file',
        ),
    ]
