# Generated by Django 5.0.2 on 2024-06-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0005_remove_vacationrequest_employee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='hr_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='hr_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
