# Generated by Django 5.0.2 on 2024-06-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0006_vacationrequest_hr_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacationrequest',
            name='reason',
        ),
    ]
