# Generated by Django 5.0.2 on 2024-06-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0007_remove_vacationrequest_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationrequest',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=100),
        ),
    ]
