# Generated by Django 5.0.2 on 2024-06-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0008_vacationrequest_observation_vacationrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacationrequest',
            old_name='observation',
            new_name='comment',
        ),
    ]
