# Generated by Django 5.0.2 on 2024-06-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0010_alter_vacationrequest_hr_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacationrequest',
            old_name='hr_approved',
            new_name='hr_approbation',
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='manager_approbation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='payroll_approbation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacationrequest',
            name='payroll_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
