# Generated by Django 5.0.2 on 2024-06-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0011_rename_hr_approved_vacationrequest_hr_approbation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacationrequest',
            options={'permissions': [('payroll_approbation', 'Can approve payroll')]},
        ),
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('APROBADA', 'APROBADA'), ('RECHAZADA', 'RECHAZADA'), ('CANCELADA', 'CANCELADA')], default='PENDIENTE', max_length=100),
        ),
    ]
