# Generated by Django 5.0.7 on 2024-08-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0014_alter_vacationrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacationrequest',
            old_name='uploaded_at',
            new_name='created_at',
        ),
    ]
