# Generated by Django 5.0.7 on 2024-09-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0016_vacationrequest_sat_is_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('APROBADA', 'APROBADA'), ('RECHAZADA', 'RECHAZADA'), ('CANCELADA', 'CANCELADA')], default='PENDIENTE', max_length=100),
        ),
    ]
