# Generated by Django 5.0.8 on 2024-10-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0018_rename_hr_approbation_vacationrequest_hr_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacationrequest',
            options={'permissions': [('payroll_approval', 'Can approve payroll')]},
        ),
    ]
