# Generated by Django 5.0.2 on 2024-02-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('identification', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('days', models.IntegerField(max_length=2)),
                ('biweekly_period', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus_paycheck', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_earnings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('healthcare_contribution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pension_contribution', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_withholding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('additional_deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
