# Generated by Django 5.0.2 on 2024-02-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='days',
            field=models.IntegerField(),
        ),
    ]
