# Generated by Django 5.0.2 on 2024-02-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_payslip_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='apsalpen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
