# Generated by Django 5.0.2 on 2024-02-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_payslip_apsalpen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payslip',
        ),
    ]
