# Generated by Django 5.0.7 on 2024-08-01 15:04

import django.utils.timezone
from datetime import timedelta
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name="answer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="answer",
            name="duration",
            field=models.DurationField(default=timedelta(hours=1)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
