# Generated by Django 5.0.7 on 2024-08-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_answer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='question_1',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='question_2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='answer',
            name='question_3',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
