# Generated by Django 5.0.8 on 2024-10-10 14:54

import django.db.models.deletion
import pqrs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('pqrs', '0001_initial'), ('pqrs', '0002_complaint_area_congratulation_area_other_area_and_more'), ('pqrs', '0003_alter_complaint_area_alter_congratulation_area_and_more'), ('pqrs', '0004_alter_complaint_area_alter_congratulation_area_and_more')]

    initial = True

    dependencies = [
        ('hierarchy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(validators=[pqrs.models.validate_max_length_2000])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('resolution_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hierarchy.area')),
            ],
        ),
        migrations.CreateModel(
            name='Congratulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(validators=[pqrs.models.validate_max_length_2000])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hierarchy.area')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(validators=[pqrs.models.validate_max_length_2000])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('resolution_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hierarchy.area')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(validators=[pqrs.models.validate_max_length_2000])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('resolution_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hierarchy.area')),
            ],
        ),
    ]
