# Generated by Django 5.0 on 2023-12-20 09:28

import django.db.models.deletion
import pqrs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
        ('pqrs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hierarchy.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='congratulation',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hierarchy.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='other',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hierarchy.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hierarchy.area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(validators=[pqrs.models.validate_max_length_2000]),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='congratulation',
            name='description',
            field=models.TextField(validators=[pqrs.models.validate_max_length_2000]),
        ),
        migrations.AlterField(
            model_name='other',
            name='description',
            field=models.TextField(validators=[pqrs.models.validate_max_length_2000]),
        ),
        migrations.AlterField(
            model_name='other',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='description',
            field=models.TextField(validators=[pqrs.models.validate_max_length_2000]),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
