# Generated by Django 5.0 on 2024-01-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0002_complaint_area_congratulation_area_other_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='area',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='congratulation',
            name='area',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='other',
            name='area',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='area',
            field=models.CharField(max_length=60),
        ),
    ]
