# Generated by Django 5.0 on 2024-01-05 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
        ('pqrs', '0003_alter_complaint_area_alter_congratulation_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hierarchy.area'),
        ),
        migrations.AlterField(
            model_name='congratulation',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hierarchy.area'),
        ),
        migrations.AlterField(
            model_name='other',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hierarchy.area'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hierarchy.area'),
        ),
    ]
