# Generated by Django 5.0.7 on 2024-09-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
