# Generated by Django 5.0.7 on 2024-09-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_image', '0002_banner_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.IntegerField(),
        ),
    ]
