# Generated by Django 5.0.7 on 2024-09-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carousel_image', '0003_alter_banner_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='active',
        ),
    ]
