# Generated by Django 5.0 on 2024-01-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='name',
            new_name='vacancy_name',
        ),
    ]
