# Generated by Django 5.0 on 2024-02-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0004_rename_refer_to_reference_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='vacancy_name',
            new_name='name',
        ),
    ]
