# Generated by Django 5.0.2 on 2024-02-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_vacancy_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='active',
            new_name='is_active',
        ),
    ]
