# Generated by Django 5.0.2 on 2024-02-19 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0007_rename_active_vacancy_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reference',
            constraint=models.UniqueConstraint(fields=('made_by', 'vacancy'), name='unique_reference'),
        ),
    ]
