# Generated by Django 5.0.2 on 2024-02-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0008_reference_unique_reference'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reference',
            name='unique_reference',
        ),
    ]
