# Generated by Django 5.0.2 on 2024-07-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0006_alter_payslip_surcharge_holiday_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='solidarity_fund',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='solidarity_fund_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
    ]
