# Generated by Django 5.0.2 on 2024-07-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0007_payslip_solidarity_fund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='solidarity_fund_percentage',
            field=models.DecimalField(decimal_places=3, max_digits=3),
        ),
    ]
