# Generated by Django 5.0.8 on 2024-10-07 11:58

import sys

from django.core.mail import mail_admins
from django.db import migrations


def create_default_groups(apps, schema_editor):
    # Get models through the `apps` registry to ensure consistency
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("users", "User")

    # Create the default groups
    coexistence_committee, _ = Group.objects.get_or_create(name="coexistence_committee")
    sst, created = Group.objects.get_or_create(name="SST")

    # If SST group was created, assign permissions and users
    if created:
        # Assign permissions from 'coexistence_committee' to 'SST'
        sst.permissions.add(*coexistence_committee.permissions.all())

        # Add HR Manager and SST Manager to the group (if they exist)
        hr_manager = User.objects.filter(
            job_position__name="GERENTE DE GESTION HUMANA"
        ).first()
        sst_manager = User.objects.filter(
            job_position__name="DIRECTOR(A) DE SEGURIDAD Y SALUD EN EL TRABAJO, GESTION AMBIENTAL Y BIENESTAR INTEGRAL"
        ).first()
        if hr_manager and sst_manager:
            hr_manager.groups.add(sst)
        else:
            if not "test" in sys.argv:
                print("User not found for HR Manager or SST Manager")
                mail_admins(
                    "Error creating SST group",
                    f"User not found for HR Manager or SST Manager. HR Manager: {hr_manager}, SST Manager: {sst_manager}",
                )


class Migration(migrations.Migration):

    dependencies = [
        ("coexistence_committee", "0002_alter_complaint_reason_delete_reason"),
    ]

    operations = [
        migrations.RunPython(create_default_groups),
    ]
