# Generated by Django 5.0 on 2024-02-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operational_risk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='events',
            table=None,
        ),
    ]
