# Generated by Django 5.0 on 2024-02-02 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_risk', '0003_eventclass_level_process_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='event_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operational_risk.eventclass'),
        ),
        migrations.AlterField(
            model_name='events',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operational_risk.level'),
        ),
        migrations.AlterField(
            model_name='events',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operational_risk.process'),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='lost_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operational_risk.losttype'),
        ),
    ]
