# Generated by Django 5.0 on 2024-02-02 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_risk', '0005_alter_events_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='accounting_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='product_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operational_risk.productline'),
        ),
    ]
