# Generated by Django 5.0 on 2024-02-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_risk', '0006_productline_alter_events_accounting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
