# Generated by Django 5.0 on 2024-02-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_risk', '0007_alter_events_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event',
        ),
        migrations.AddField(
            model_name='events',
            name='event_title',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
