# Generated by Django 5.0 on 2024-02-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_risk', '0009_alter_events_description_alter_events_learning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='accounting_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='date_of_closure',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='discovery_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
