# Generated by Django 5.0 on 2024-02-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operational_risk', '0010_alter_events_accounting_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='product_line',
            new_name='product',
        ),
    ]
