# Generated by Django 5.0 on 2024-02-02 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operational_risk', '0011_rename_product_line_events_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='date_of_closure',
            new_name='close_date',
        ),
    ]
