# Generated by Django 5.0.2 on 2024-04-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operational_risk', '0012_rename_date_of_closure_events_close_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='accounting_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='close_date',
            field=models.DateField(),
        ),
    ]
